### ISSUE TITLE
Feature: User can see list of top headings on home page

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see list of top headings on home page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When you first get to the site you see a list of top headings to click on

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="206" alt="feature1 1" src="https://user-images.githubusercontent.com/99702540/171042261-8b365318-cb5b-4ee6-92e6-f08607919295.png">
<img width="301" alt="feature1 2" src="https://user-images.githubusercontent.com/99702540/171042269-1708d065-fae5-4c3a-b4b0-3a6581a97ee5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create an app.jsx with a navbar and top headings page being rendered
- [x] Create a component to render a navbar
- [x] Make it so the links get pushed into a drop down on smaller screens
- [x] Create a component to render a top headings list from the gnews api
- [x] Send a fetch request to the api
- [x] Display results on the page in proper columns and rows

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
