### ISSUE TITLE
Feature: User can search for articles by keyword and language

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for articles by keyword and language

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When you click the search icon in the navbar your are brought to a page that lets you search for articles by keyword and language

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="102" alt="feature10 1" src="https://user-images.githubusercontent.com/99702540/171044889-c4d8f409-f686-4c31-b4b6-da88942b5f6e.png">
<img width="295" alt="feature10 2" src="https://user-images.githubusercontent.com/99702540/171044897-02af296e-ec94-4df7-96a1-9972a8d907f6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to display the search page
- [x] In the search page create a submit handler that queries the api for the keyword input
- [x] Update navbar component to contain a link to the search page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
