### ISSUE TITLE
Feature: User can view list of search results

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view list of search results

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When clicking the search button you are brought to a new page displaying the list of search results

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="298" alt="feature11 1" src="https://user-images.githubusercontent.com/99702540/171045184-f958b156-9e4f-4fe3-a8aa-864775f2fc62.png">
<img width="205" alt="feature11 2" src="https://user-images.githubusercontent.com/99702540/171045192-b7a800c5-58da-4f48-a863-f974905483ba.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to display search result on the page
- [x] Create a component to display the individual result
- [x] In each results href have a link back to info with the articles info
- [x] Update search-form component to have a condition in render to redirect to search-results if articles are present

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
