### ISSUE TITLE
Feature: User can see article info

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see article info

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When you click on an article the relevant info shows in a new page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="296" alt="feature2 1" src="https://user-images.githubusercontent.com/99702540/171042571-e1ca501e-14b7-4486-909c-561aee061189.png">
<img width="102" alt="feature2 2" src="https://user-images.githubusercontent.com/99702540/171042576-948ad98e-575b-4fca-b508-a730417b1ceb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Import some dummy data into the reviewedArticles, reviews, and users tables 

### ☁️ Server

- [x] Update `server/index.js` to check if it can select the current articles title and source
- [x] If none is found then simply display the article info with no reviews
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update app.jsx to have a componentDidMount hashchange event listener that parses the hash and sets the route containing the path and params into the state.
- [x] Create a parseRoute helper function that properly splits the hash before setting the route to the state.
- [x] Update app.jsx to have a render page method and decide what component to render based off route.path
- [x] Create a component to use the selected articles info to send a request to the database to check to see if the article is reviewed.
- [x] If not then display the default information

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
