### ISSUE TITLE
Feature: User can see rating percentages

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see rating percentages

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When you view an article that has reviews you can see rating percentages under it

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="292" alt="Screenshot 2022-06-10 154514" src="https://user-images.githubusercontent.com/99702540/173159776-9aac7ba0-d5e4-430b-afd9-42f231040d30.png">
<img width="190" alt="Screenshot 2022-06-10 154531" src="https://user-images.githubusercontent.com/99702540/173159781-7384b74d-435e-4d67-95e8-62cb05cabf24.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [ ] Update `server/index.js` to sum the total number of one rating and the total number of ratings
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to display the percentages received from the database
- [ ] In the componentDidMount put a fetch request to get number of each rating type for that articleId
- [ ] Update article-info component to append the percentages component in the layout

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
