### ISSUE TITLE
Feature: User can sign in

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When you click either the link in the nav or review button on the info page you get brought to a sign in page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="100" alt="feature4 1" src="https://user-images.githubusercontent.com/99702540/171043055-4d678810-f175-4418-b7f5-bf28120b0439.png">
<img width="295" alt="feature4 2" src="https://user-images.githubusercontent.com/99702540/171043057-acd53b4b-3368-44b9-ac76-01a3eb3ab830.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a route for sign-in to get a token once user is verified 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update app.jsx component to also include sign in with the sign up route
- [x] Create methods for signing in and signing out by setting and removing the token from local storage
- [x] Include the user and the handleSignIn/handleSignOut methods in the context
- [x] In review form make it so the article posted is using the username and userId rather than the dummy data
- [x] Make sure the x access token is included in all post req
- [x] Add styling and alternate action changes to the authform so that the sign in and sign up can use the same page
- [x] Add conditions to the fetch so the endpoint changes based on the path
- [x] Add a condition in review form to redirect to sign in if user is not present

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
