### ISSUE TITLE
Feature: User can sign up

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When you click the sign up link on the sign in page it brings you to a new page to register

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="301" alt="feature5 1" src="https://user-images.githubusercontent.com/99702540/171043333-64db133f-7db3-4826-ace1-ea59bd5439fd.png">
<img width="208" alt="feature5 2" src="https://user-images.githubusercontent.com/99702540/171043338-d8d5b7d0-2ae6-44b2-b5d0-dee615c8dc78.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a post req route that handles signing up
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the sign up forms structure
- [x] In this component make sure a user isn't already present before proceeding
- [x] Create a component to render the inputs of the sign up form based on path
- [x] Update app.jsx component to have a renderPage route to the sign up page
- [x] Also add properties in state to hold the user and isAuthorizing

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
