### ISSUE TITLE
Feature: User can review and rate an article

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can review and rate an article

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When you click the review button on the info page or get re directed from sign up, you get taken to a form to input a rating and review

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="98" alt="feature6 1" src="https://user-images.githubusercontent.com/99702540/171043803-921d91b2-84a8-4d5a-9dfc-82f4e6106310.png">
<img width="294" alt="feature6 2" src="https://user-images.githubusercontent.com/99702540/171043808-4fedcc56-5615-4b55-a282-0f20e7b0e7ca.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to post the article to the reviewedArticles table
- [x] Update `server/index.js` to post the user review to the reviews table
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to use a form to accept user inputs
- [x] In that form send a fetch request to post data
- [x] Update the article-info page to hashchange to review form
- [x] Update app.jsx to render the review form when route allows

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
