### ISSUE TITLE
Feature: User can view list of reviewed articles

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view list of reviewed articles

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When you click submit on the review form you get taken to a reviews page that shows a list of your reviews and a link to the article

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="299" alt="feature7 1" src="https://user-images.githubusercontent.com/99702540/171044174-c4d3f8c0-de14-47b2-8969-18d82a5c58e4.png">
<img width="96" alt="feature7 2" src="https://user-images.githubusercontent.com/99702540/171044182-639ffe23-d0bd-4e8b-b951-949a30f092fb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a route to select all reviews based on user id
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display a list of the current users reviews
- [x] In this component send a fetch request to get the user reviews and put them in state
- [x] Add a method that also searches for the article the review goes with based on article id
- [x] Add a method that moves back to article info with the correct article info passed as props
- [x] Update app.jsx to have a redirect to the reviews page
- [x] Update navbar to have a path to reviews page

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
