### ISSUE TITLE
Feature: User can view other users reviews

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view other users reviews

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When on the article info page you can scroll down to see reviews and ratings left by other users

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="296" alt="feature2 1" src="https://user-images.githubusercontent.com/99702540/171044345-19ec0115-a7d9-405f-b0db-b757ffc35d56.png">
<img width="102" alt="feature2 2" src="https://user-images.githubusercontent.com/99702540/171044348-d66de602-9544-4d9b-82e0-cf47904e340d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to pull all reviews based on articleId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display the reviews fetched in componentDidMount
- [x] Create another component that will be in the map of the previous to list each review
- [x] Update article-info component to have a second section that displays the total user review component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
